#!/bin/sh
set -e

if [ -x "/etc/init.d/arangodb3" ]; then
	invoke-rc.d arangodb3 stop || exit $?
fi

if [ -d /run/systemd/system ] ; then
        if systemctl list-unit-files | grep -q arangodb3e.service ; then
            deb-systemd-invoke stop arangodb3e.service
        fi
fi
