#!/bin/sh
me=$(realpath "$0")
program=$(basename "$me")
installation=$(dirname "$(dirname "$me")")
executable=$installation/usr/bin/$program
if [ -x "$executable" ] ; then
  exec "$executable" \
       --configuration none \
       --console.pretty-print true \
       --server.endpoint tcp://127.0.0.1:8529 \
       --server.authentication false \
       --server.ask-jwt-secret true \
       --javascript.startup-directory "$installation/usr/share/arangodb3/js" \
       --javascript.client-module inspector.js \
       "$@"
fi
echo "Could not find executable!"
exit 1
