#!/bin/sh
me=$(realpath $0)
program=$(basename $me)
installation=$(dirname $(dirname $me))
executable=$installation/usr/bin/$program
if [ -x $executable ] ; then
  exec $executable --server.arangod=$installation/usr/sbin/arangod --server.js-dir=$installation/usr/share/arangodb3/js "$@"
fi
echo "Could not find executable!"
exit 1
