#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
export NVM_DIR=/usr/local/nvm
. $NVM_DIR/nvm.sh
nvm use stable

#add options
skip_examples=true
skip_swagger=true

type gitbook &>/dev/null || { echo "gitbook not installed"; exit; }
type ditaa &>/dev/null || { echo "dittaa not installed"; exit; }

# oskar work dir - or a directory that contains a checkout in a sub folder
export ARANGO_WORK=${ARANGO_WORK:-"/work"}

# path to arangodb source
export ARANGO_SOURCE="$ARANGO_WORK/ArangoDB"
export ARANGO_SOURCE_BOOKS="$ARANGO_SOURCE/Documentation/Books"

# path to documentation build
export ARANGO_BUILD="$ARANGO_WORK/build-documentation"
export ARANGO_BUILD="$ARANGO_SOURCE_BOOKS" ## TODO FIXME - we can not freely select the output dir
export ARANGO_BUILD_PPDIR="$ARANGO_BUILD/ppdir"
export ARANGO_BUILD_BOOKS="$ARANGO_BUILD/books"


cd "$ARANGO_SOURCE" || { echo "could not change in arangodb source directroy"; exit 1; }
echo $(pwd)
ls -lisah ./build &>/dev/null || echo "no build directory"
ls -lisah ./build/bin &>/dev/null || echo "unable to access source/bild/bin"

[[ -e ./build/bin/arangod ]] || { echo "no arangod installed"; exit 1; }

if $skip_examples; then
  echo "skip generate examples"
else
  ./utils/generateExamples.sh || { echo "failed to generate examples!"; exit 1; }
fi

if $skip_swagger; then
  echo "skip generate swagger"
else
  ./utils/generateSwagger.sh || { echo "failed to generate swagger"; exit 1; }
fi

cd "$ARANGO_SOURCE_BOOKS"
# get gitbook version
echo "calling build_documenation"
"$script_dir/build_documentation" build-books

exit $?
