#!/bin/bash
export NVM_DIR=/usr/local/nvm
. $NVM_DIR/nvm.sh
nvm use stable

install_lockfile(){
    # install lockfile - do we still need this?
    pip install lockfile
}

install_ditaa(){
    # work around broken binfmt_misc support:
    rm -f /usr/bin/ditaa
    printf '#!/bin/bash
    java -jar /usr/share/ditaa/ditaa.jar $@
    ' > /usr/bin/ditaa
    chmod a+x /usr/bin/ditaa
}

install_bash_lib(){
    ## get bash_lib - code works without this lib ## TODO set to fixed versioin
    OBI_VERSION="add3758b5437802d89241363c4f78547ed93304e"
    OBI_VERSION="master"
    wget https://raw.githubusercontent.com/ObiWahn/config/${OBI_VERSION}/etc/skel.obi/.bashrc.d/all/bash_lib || true
}

## run installations
#install_lockfile
install_ditaa
install_bash_lib
