#!/bin/bash

ferr(){ echo "$@"; exit 1; }
export NVM_DIR=${NVM_DIR:-"/usr/local/nvm"}
. $NVM_DIR/nvm.sh || ferr "could not source nvm"

[[ -v ARANGO_SUPPORTED_BRANCHES ]] || ferr "supported branches not set"
[[ -v ARANGO_CACHE_BASE ]] || ferr "arango cache base not set";

nvm use stable || ferr "could not use nvm"
npm install gitbook-cli -g || ferr "could not install gitbook-cli"

cache_base="$ARANGO_CACHE_BASE"
mkdir -p "$cache_base" && cd "$cache_base" || ferr "failed to create cache dir"

for i in $ARANGO_SUPPORTED_BRANCHES; do
    cache="$cache_base/$i"
    mkdir -p "$cache"
    cd "$cache"

    for book in AQL HTTP Manual Cookbook Drivers; do
        cd "$cache"
        echo "Installing modules for book: $book in version $i"
        mkdir "$book" && cd "$book"
        rm -fr book.json
        url="https://raw.githubusercontent.com/arangodb/arangodb/"
        url+="$i/Documentation/Books/${book}/book.json"
        if ! curl --fail -O "$url"; then
            echo "could not download $url continue"
            continue
        fi

        ## replace templates with some random strings so we
        ## are able to install
        sed -e "s;@GCHANGE_FREQ@;daily;" \
            -e "s;@GPRIORITY@;0.3;" \
            -i "book.json" || ferr "failed to replace templates"

        echo "calling 'gitbook install' on 'book.json' : << HERE"
        cat book.json
        echo "HERE"

        gitbook install -g &> book_install.log || { echo "Failed to install modules"; cat book.json; exit 1; }
        mv book.json book.json_at_install
    done
done 2>&1 | tee set_gitbook.log

chmod 777 "$ARANGO_CACHE_BASE"

echo "git book modules successfully installed"
