#!/bin/bash

install_lockfile(){
    # install lockfile - do we still need this?
    pip install lockfile
}

install_ditaa(){
    # work around broken binfmt_misc support:
    rm -f /usr/bin/ditaa
    printf '#!/bin/bash
    java -jar /usr/share/ditaa/ditaa.jar $@
    ' > /usr/bin/ditaa
    chmod a+x /usr/bin/ditaa
}

install_bash_lib(){
    ## get bash_lib - code works without this lib ## TODO set to fixed versioin
    OBI_VERSION="arango"
    cd $ARANGO_INSTALL
    wget https://raw.githubusercontent.com/ObiWahn/config/${OBI_VERSION}/etc/skel.obi/.bashrc.d/all/bash_lib || true
    chmod 666 bash_lib
}

## run installations

#install_lockfile
install_ditaa
install_bash_lib

echo "setup done"
