#!/bin/bash
export NVM_DIR=/usr/local/nvm
. $NVM_DIR/nvm.sh
nvm use stable || { echo "could not use nvm"; exit 1; }
npm install gitbook-cli -g || { echo "could not install gitbook-cli"; exit 1; }

cache_base="/root/gitbook_cache"
mkdir -p "$cache_base"
cd "$cache_base"
creation_date <<<"$(date)"

for i in 3.0 3.1 3.2 3.3 3.4 devel; do
    cache="$cache_base/$i"
    mkdir -p "$cache"
    cd "$cache"

    for book in AQL HTTP Manual Cookbook Drivers; do
        cd "$cache"
        echo "Installing modules for book: $book in version $i"
        mkdir "$book" && cd "$book"
        rm -fr book.json
        if ! curl --fail -O https://raw.githubusercontent.com/arangodb/arangodb/$i/Documentation/Books/${book}/book.json; then
            echo "could not download: https://raw.githubusercontent.com/arangodb/arangodb/$i/Documentation/Books/${book}/book.json continue"
            continue
        fi

        sed -e "s;@GCHANGE_FREQ@;daily};" \
            -e "s;@GPRIORITY@;0.3;" \
            -i "book.json"

        echo "calling 'gitbook install' on 'book.json' : << HERE"
        cat book.json
        echo "HERE"

        gitbook install -g &> book_install.log || { echo "Failed to install modules"; cat book.json; exit 1; }
        mv book.json book.json_at_install
    done
done

echo "git book modules successfully installed"
