#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$script_dir/lib/oskar.bash"

containerdir="$script_dir/../containers/documentation.docker"

## parse args
force_update=false
for arg in "$@"; do
    case $arg in
        --force-update)
            force_update=true
        ;;
        *)
        ;;
    esac
done

## build command
cmd=( "docker" "build"
      "-t" "$arango_doc_container_default"
    )
if $force_update; then
    cmd+=( "--build-arg" "FORCE_UPDATE=$(date --iso-8601=seconds)" )
fi
cmd+=( "$containerdir" )

## execute command
echo "calling ${cmd[@]}"
sleep 1
${cmd[@]}
