#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$script_dir/lib/oskar.bash"

#
# Without additional flags this script builds and tests the documentation in html format.
# It requires a functional build in work/Arangodb/build!
#
# flags:
# --books "string with spaces"   -- list of books to build or test
# --all-formats                  -- do not build http only
# --checks                       -- only run checks - book must have been build
# --cross-checks                 -- only run cross book checks - books must have been build

# examples:
# ./scripts/buildDocumenation
# ./scropts/buildDocumenation --books "HTTP Drivers"
# ./scripts/buildDocumenation --skip-examples --skip-swagger
# ./scripts/buildDocumenation --all-formats
# ./scropts/buildDocumenation --checks
# ./scropts/buildDocumenation --checks --books "HTTP Drivers"



oskar_dir="$script_dir/../"

[[ -n $oskar_dir ]] || ferr "no source dir given"

cmd=( docker
      run
      -v "$oskar_dir:/oskar"
      -t "$arango_doc_container_default"
      --uid $UID
      --
      "$@"
    )

echo "calling ${cmd[@]}"
"${cmd[@]}"
