#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
. "$script_dir/lib/oskar.bash"

oskar_work="${1:-"$script_dir/../work"}"

[[ -n $oskar_work ]] || ferr "no source dir given"

cmd=( docker
      run
      -v "$oskar_work:/work"
      -t "$arango_doc_container_default"
    )
    #--uid $UID

echo "calling ${cmd[@]}"
"${cmd[@]}"
