#!/usr/bin/expect -f

#possible improvement / replacement
#https://unix.stackexchange.com/questions/328601/rpmsign-with-cli-password-prompt

### rpm-sign.exp -- Sign RPMs by sending the passphrase.
set timeout -1

set password $env(ARANGO_SIGN_PASSWD)
send_user "## EXPECT ## '$password'\n"
spawn rpm --define "_gpg_name <info@arangodb.com>" --addsign {*}$argv

expect {
    "Enter pass phrase:" {
        send -- "$password\r"
    }
}
## end of rpm-sign.exp
